import { signUp } from "./User";

export async function makeManyUser() {
  const users = [
    {
      email: "actionhero@example.com",
      pw: "Qwerty12!",
      name: "액션스타",
      gender: "MALE",
      age: 28,
      nation: "대한민국",
      bio: "액션과 슈팅 게임을 가장 좋아합니다.",
      imgPath: null,
      favCategory1: "ACTION",
      favCategory2: "STRATEGY",
      favCategory3: "ADVENTURE",
    },
    {
      email: "rhythmqueen@example.com",
      pw: "Qwerty12!",
      name: "박자퀸",
      gender: "FEMALE",
      age: 22,
      nation: "대한민국",
      bio: "리듬게임과 비주얼노벨이 인생입니다.",
      imgPath: null,
      favCategory1: "CASUAL",
      favCategory2: "RACING",
      favCategory3: "ADVENTURE",
    },
    {
      email: "fightingfan@example.com",
      pw: "Qwerty12!",
      name: "싸움꾼",
      gender: "NONE",
      age: 30,
      nation: "대한민국",
      bio: "격투 및 무술 게임을 좋아합니다.",
      imgPath: null,
      favCategory1: "ROLE_PLAYING",
      favCategory2: "ACTION",
      favCategory3: "ADVENTURE",
    },
    {
      email: "adventurelover@example.com",
      pw: "Qwerty12!",
      name: "모험남",
      gender: "MALE",
      age: 25,
      nation: "대한민국",
      bio: "모험 게임을 사랑합니다.",
      imgPath: null,
      favCategory1: "ADVENTURE",
      favCategory2: "CASUAL",
      favCategory3: "ROLE_PLAYING",
    },
    {
      email: "puzzlemaster@example.com",
      pw: "Qwerty12!",
      name: "퍼즐천재",
      gender: "FEMALE",
      age: 35,
      nation: "대한민국",
      bio: "다양한 퍼즐 게임을 즐깁니다.",
      imgPath: null,
      favCategory1: "CASUAL",
      favCategory2: "ADVENTURE",
      favCategory3: "ROLE_PLAYING",
    },
    {
      email: "roguelikeking@example.com",
      pw: "Qwerty12!",
      name: "로그황제",
      gender: "NONE",
      age: 18,
      nation: "대한민국",
      bio: "로그라이크 게임에 푹 빠져있습니다.",
      imgPath: null,
      favCategory1: "RACING",
      favCategory2: "ACTION",
      favCategory3: "ADVENTURE",
    },
    {
      email: "rpgmaster@example.com",
      pw: "Qwerty12!",
      name: "롤플레잉고수",
      gender: "MALE",
      age: 31,
      nation: "대한민국",
      bio: "RPG 게임을 사랑합니다.",
      imgPath: null,
      favCategory1: "ROLE_PLAYING",
      favCategory2: "ADVENTURE",
      favCategory3: "STRATEGY",
    },
    {
      email: "simulationguru@example.com",
      pw: "Qwerty12!",
      name: "시뮬레이터왕",
      gender: "FEMALE",
      age: 26,
      nation: "대한민국",
      bio: "다양한 시뮬레이션 게임을 합니다.",
      imgPath: null,
      favCategory1: "SIMULATION",
      favCategory2: "CASUAL",
      favCategory3: "STRATEGY",
    },
    {
      email: "farmingpro@example.com",
      pw: "Qwerty12!",
      name: "농장지기",
      gender: "NONE",
      age: 19,
      nation: "대한민국",
      bio: "농장 및 크래프팅 게임을 좋아합니다.",
      imgPath: null,
      favCategory1: "SIMULATION",
      favCategory2: "STRATEGY",
      favCategory3: "ADVENTURE",
    },
    {
      email: "datingmaster@example.com",
      pw: "Qwerty12!",
      name: "데이트고수",
      gender: "MALE",
      age: 27,
      nation: "대한민국",
      bio: "데이팅 시뮬레이션 게임에 관심이 많습니다.",
      imgPath: null,
      favCategory1: "SIMULATION",
      favCategory2: "CASUAL",
      favCategory3: "ROLE_PLAYING",
    },
    {
      email: "strategygod@example.com",
      pw: "Qwerty12!",
      name: "전략신",
      gender: "FEMALE",
      age: 33,
      nation: "대한민국",
      bio: "전략 시뮬레이션 게임을 잘합니다.",
      imgPath: null,
      favCategory1: "STRATEGY",
      favCategory2: "ROLE_PLAYING",
      favCategory3: "ADVENTURE",
    },
    {
      email: "rtsmastermind@example.com",
      pw: "Qwerty12!",
      name: "실시간전략천재",
      gender: "NONE",
      age: 24,
      nation: "대한민국",
      bio: "실시간 전략 게임이 최고입니다.",
      imgPath: null,
      favCategory1: "STRATEGY",
      favCategory2: "RACING",
      favCategory3: "ACTION",
    },
    {
      email: "sportsgamer@example.com",
      pw: "Qwerty12!",
      name: "스포츠마니아",
      gender: "MALE",
      age: 29,
      nation: "대한민국",
      bio: "스포츠와 레이싱 게임을 좋아합니다.",
      imgPath: null,
      favCategory1: "SPORTS",
      favCategory2: "RACING",
      favCategory3: "ACTION",
    },
    {
      email: "rpgwarrior@example.com",
      pw: "Qwerty12!",
      name: "롤플레잉전사",
      gender: "FEMALE",
      age: 21,
      nation: "대한민국",
      bio: "RPG 게임 속 세계에 빠져듭니다.",
      imgPath: null,
      favCategory1: "ROLE_PLAYING",
      favCategory2: "ADVENTURE",
      favCategory3: "STRATEGY",
    },
    {
      email: "fightingchamp@example.com",
      pw: "Qwerty12!",
      name: "격투왕",
      gender: "NONE",
      age: 32,
      nation: "대한민국",
      bio: "격투 게임에서 실력을 발휘합니다.",
      imgPath: null,
      favCategory1: "ACTION",
      favCategory2: "CASUAL",
      favCategory3: "ADVENTURE",
    },
    {
      email: "adventurequeen@example.com",
      pw: "Qwerty12!",
      name: "모험퀸",
      gender: "FEMALE",
      age: 23,
      nation: "대한민국",
      bio: "모험 게임 속 세계를 탐험하는 것을 좋아합니다.",
      imgPath: null,
      favCategory1: "ADVENTURE",
      favCategory2: "CASUAL",
      favCategory3: "ROLE_PLAYING",
    },
    {
      email: "puzzlewizard@example.com",
      pw: "Qwerty12!",
      name: "퍼즐마법사",
      gender: "MALE",
      age: 36,
      nation: "대한민국",
      bio: "퍼즐 게임을 푸는 것이 재미있습니다.",
      imgPath: null,
      favCategory1: "ROLE_PLAYING",
      favCategory2: "ADVENTURE",
      favCategory3: "CASUAL",
    },
    {
      email: "roguelikemaster@example.com",
      pw: "Qwerty12!",
      name: "로그라이크고수",
      gender: "NONE",
      age: 27,
      nation: "대한민국",
      bio: "로그라이크 게임의 마스터입니다.",
      imgPath: null,
      favCategory1: "RACING",
      favCategory2: "ACTION",
      favCategory3: "ADVENTURE",
    },
    {
      email: "rhythmking@example.com",
      pw: "Qwerty12!",
      name: "박자킹",
      gender: "MALE",
      age: 20,
      nation: "대한민국",
      bio: "리듬게임에서 최고의 실력을 자랑합니다.",
      imgPath: null,
      favCategory1: "ACTION",
      favCategory2: "CASUAL",
      favCategory3: "SIMULATION",
    },
    {
      email: "farmingexpert@example.com",
      pw: "Qwerty12!",
      name: "농장고수",
      gender: "FEMALE",
      age: 17,
      nation: "대한민국",
      bio: "농장과 크래프팅 게임이 최고입니다.",
      imgPath: null,
      favCategory1: "CASUAL",
      favCategory2: "SIMULATION",
      favCategory3: "ADVENTURE",
    },
  ];

  users.forEach((user) => {
    signUp(user).then((res) => {
      console.log(res);
    });
  });
}
